image: eclipse-temurin:11-jdk
services:
  - name: docker:dind
    command: [ "--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./mvnw compile

test:
  stage: test
  script:
    - ./mvnw test
