image: eclipse-temurin:11-jdk
services:
  - name: docker:dind
    command: [ "--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - './mvnw $MAVEN_CLI_OPTS compile'

test:
  stage: test
  script:
    - './mvnw $MAVEN_CLI_OPTS test'
  artifacts:
    when: always
    reports:
      junit:
        - chat-bot-core/target/surefire-reports/*.xml
        - chat-bot-telegram-ui/target/surefire-reports/*.xml
        - debt-tracker-core/target/surefire-reports/*.xml
        - debt-tracker-misc/target/surefire-reports/*.xml
        - debt-tracker-persistence/target/surefire-reports/*.xml
        - debt-tracker-service/target/surefire-reports/*.xml
        - debt-tracker-web/target/surefire-reports/*.xml
        - simple-chat-bot/target/surefire-reports/*.xml

integration-test:
  stage: integration-test
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'