image: eclipse-temurin:11-jdk
services:
  - name: docker:dind
    command: [ "--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

stages:
  - build
  - test
  - integration-test

build:
  stage: build
  script:
    - './mvnw $MAVEN_CLI_OPTS compile'

test:
  stage: test
  script:
    - './mvnw $MAVEN_CLI_OPTS test'

integration-test:
  stage: integration-test
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'