ALTER TABLE INCOMES ADD COLUMN ENTRY_DATE TIMESTAMP DEFAULT localtimestamp;
UPDATE INCOMES SET ENTRY_DATE = localtimestamp WHERE ENTRY_DATE IS NULL;
ALTER TABLE INCOMES ALTER COLUMN ENTRY_DATE SET NOT NULL;
ALTER TABLE INCOMES ALTER COLUMN ENTRY_DATE DROP DEFAULT;

ALTER TABLE EXPENSES ADD COLUMN ENTRY_DATE TIMESTAMP DEFAULT localtimestamp;
UPDATE EXPENSES SET ENTRY_DATE = localtimestamp WHERE ENTRY_DATE IS NULL;
ALTER TABLE EXPENSES ALTER COLUMN ENTRY_DATE SET NOT NULL;
ALTER TABLE EXPENSES ALTER COLUMN ENTRY_DATE DROP DEFAULT;

