CREATE TABLE ACCOUNT
(
    ID      BIGSERIAL,
    CHAT_ID BIGINT NOT NULL,
    NAME    VARCHAR(32) NOT NULL,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID),
    CONSTRAINT ACCOUNT_CHAT_ID_NAME_UNIQUE UNIQUE (CHAT_ID, NAME),
    CONSTRAINT ACCOUNT_CHAT_ID_FKEY FOREIGN KEY (CHAT_ID) REFERENCES CHAT(ID)
);

CREATE INDEX ACCOUNT_CHAT_ID_IDX ON ACCOUNT(CHAT_ID);
