CREATE SEQUENCE HIBERNATE_SEQUENCE AS BIGINT INCREMENT BY 1 START WITH 1 OWNED BY NONE;

CREATE TABLE CHAT
(
    ID              BIGINT,
    CHAT_STATUS     VARCHAR(1) NOT NULL,
    OPERATION_TYPE  VARCHAR(1) NULL,
    CONSTRAINT CHAT_PKEY PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT
(
    ID      BIGINT,
    CHAT_ID BIGINT NOT NULL,
    NAME    VARCHAR(32) NOT NULL,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID),
    CONSTRAINT ACCOUNT_CHAT_ID_NAME_UNIQUE UNIQUE (CHAT_ID, NAME),
    CONSTRAINT ACCOUNT_CHAT_ID_FKEY FOREIGN KEY (CHAT_ID) REFERENCES CHAT(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX ACCOUNT_CHAT_ID_IDX ON ACCOUNT(CHAT_ID);
