CREATE TABLE ACCOUNT
(
    ID  BIGSERIAL PRIMARY KEY,
    CHAT_ID BIGINT NOT NULL REFERENCES CHAT,
    NAME VARCHAR(32) NOT NULL,
    UNIQUE (CHAT_ID, NAME)
);

CREATE INDEX ACCOUNT_CHAT_ID_IDX ON ACCOUNT(CHAT_ID);
