CREATE TABLE ACTIVE_CHATS
(
    ID      BIGSERIAL PRIMARY KEY,
    CHAT_ID BIGINT NOT NULL
);

CREATE TABLE INCOMES
(
    ID      BIGSERIAL PRIMARY KEY,
    CHAT_ID BIGINT NOT NULL,
    AMOUNT  NUMERIC NOT NULL CHECK (AMOUNT > 0)
);

CREATE TABLE EXPENSES
(
    ID      BIGSERIAL PRIMARY KEY,
    CHAT_ID BIGINT NOT NULL,
    AMOUNT  NUMERIC NOT NULL CHECK (AMOUNT > 0)
);
