ALTER TABLE INCOMES ADD COLUMN ENTRY_DATE TIMESTAMP;
UPDATE INCOMES SET ENTRY_DATE = localtimestamp;
ALTER TABLE INCOMES ALTER COLUMN ENTRY_DATE SET NOT NULL;

ALTER TABLE EXPENSES ADD COLUMN ENTRY_DATE TIMESTAMP;
UPDATE EXPENSES SET ENTRY_DATE = localtimestamp;
ALTER TABLE EXPENSES ALTER COLUMN ENTRY_DATE SET NOT NULL;

